# -*- coding: utf-8 -*-
"""Avi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fakiLgrKk5GGfhMwIPa-b2cf96TvtKos

Q1) you are working in a bank, and you have been given two lists of the employees who worked in 2021. Employees' names in List 1 are Ramesh, Suresh, Mahesh, Ali, Jacob, and Saritha. List 2 contains the contains the names of Ali, Mukesh, Mahesh, Jacob, Sai, and Sarita. please write a program that helps to identify people who are common in both lists. please do not use any in-build function.
"""

list1 = ["Ramesh", "Suresh", "Mahesh", "Ali", "Jacob", "Saritha"]
list2 = ["Ali", "Mukesh", "Mahesh", "Jacob", "Sai", "Sarita"]
common_names = []
for i in range(len(list1)):
    name1 = list1[i]
    is_common = False
    for j in range(len(list2)):
        name2 = list2[j]
        match = True
        for k in range(len(name1)):
            if k >= len(name2) or name1[k] != name2[k]:
                match = False
                break
        if match and len(name1) == len(name2):
            is_common = True
            break
    if is_common:
        common_names.append(name1)
print("Common names between List 1 and List 2:")
for name in common_names:
    print(name)

"""Q2) While entering data, someone entered a few names as a common string "Ramesh Suresh Mohit". Please write a program which separates all the names and converts them into a list. Once converted into a list, please write a program that adds their age.
Ramesh: 25
Suresh: 22
Mohit: 26
"""

names_string = "Ramesh Suresh Mohit"
ages = [25, 22, 26]
names_list = names_string.split()
if len(names_list) == len(ages):
    name_age_dict = {}
    for i in range(len(names_list)):
        name = names_list[i]
        age = ages[i]
        name_age_dict[name] = age
    print("Names and Ages:")
    for name, age in name_age_dict.items():
        print(f"{name}: {age}")
else:
    print("Number of names and ages don't match!")

"""Q3) You are working in a medical store. A patient came to your medical store and asked to buy 2 strips of paracetamol, 3 strips of azithromycin, and 5 strips of Vitamin C. One strip of paracetamol costs Rs 35, one strip of azithromycin costs Rs 49, and one strip of Vitamin C costs Rs 33. Patient gave you Rs 2000. Please tell us what is the total cost of each medicine, the total cost of all medicine, and how much money you refunded to the patient."""

paracetamol_cost = 35
azithromycin_cost = 49
vitamin_c_cost = 33

paracetamol_quantity = 2
azithromycin_quantity = 3
vitamin_c_quantity = 5

paracetamol_total_cost = paracetamol_cost * paracetamol_quantity
azithromycin_total_cost = azithromycin_cost * azithromycin_quantity
vitamin_c_total_cost = vitamin_c_cost * vitamin_c_quantity

total_cost = paracetamol_total_cost + azithromycin_total_cost + vitamin_c_total_cost

amount_paid = 2000

refund_amount = amount_paid - total_cost

print("Cost of Paracetamol:", paracetamol_total_cost)
print("Cost of Azithromycin:", azithromycin_total_cost)
print("Cost of Vitamin C:", vitamin_c_total_cost)
print("Total cost of all medicine:", total_cost)
print("Refund amount to the patient:", refund_amount)

"""Q4) Accept a sentence as input and find the number of vowels in it. Assume that the sentence has no punctuation marks. For example, I am learning python contains 6 vowels. This function should be applicable for all other different sentences."""

sentence = input("Enter a sentence: ")

sentence = sentence.lower()

vowel_count = 0
vowels = {'a', 'e', 'i', 'o', 'u'}

for char in sentence:
    if char in vowels:
        vowel_count += 1
print("Number of vowels:", vowel_count)

"""Q5) You have been appointed by the election commission to create a website. Your first task is to work on a program which tells candidates if they are eligible for voting or not. If they are eligible, your output should be "Congrats! You are eligible"; otherwise, it should tell that you have to return after X number of years. The eligibility criteria for voting is 18 years.                            For example, If someone is 18 or above, your output should be "Congrats! You are eligible". If someone's age is 15 years, it should print output as "return after 3 years"."""

age = int(input("Enter your age: "))

if age >= 18:
    print("Congrats! You are eligible")
else:
    years_left = 18 - age
    print("Return after", years_left, "years")

"""Q6) Given a list of integers, find the cumulative sum of the elements of the list and store them in another list. A = [1, 2, 3, 4, 5]  Output: [1, 3, 6, 10, 15]"""

A = [1, 2, 3, 4, 5]

cumulative_sum = [A[0]]

for i in range(1, len(A)):
    current_sum = cumulative_sum[i-1] + A[i]
    cumulative_sum.append(current_sum)

print(cumulative_sum)

"""Q7) WAP to encode a message entered by user as per below conditions:                                                                                                              
For every word in the sentence,                                           
1. If the word starts with a vowel, encode it as first and last letter of the word.     2. If the word starts with a consonant, remove all vowels from it.                          Ensure the case insensitive comparisions/checks are performed.  Please enter your text: The quick brown fox used to sleep inside this box.    Encoded Msg: Th qck brwn fx us t slp ie ths bx
"""

message = input("Please enter your text: ")

words = message.split()

encoded_words = []

for word in words:
    lowercase_word = word.lower()
    if lowercase_word[0] in 'aeiou':
        encoded_word = word[0] + word[-1]
    else:
        encoded_word = ''.join(char for char in word if char.lower() not in 'aeiou')

    encoded_words.append(encoded_word)
encoded_message = ' '.join(encoded_words)
print("Encoded Msg:", encoded_message)

"""Q8) Write a program to implement run length encoding of string.                                  
RLE:Consective repetition of a character has to be replaced with the count of occurrences and the character.                                                                                                        
Enter your string :aabbbccdddae                                                                                           
Encoded: 2a3b2c3d1a1e
"""

string = input("Enter your string: ")

encoded_string = ""
current_char = string[0]
count = 1

for i in range(1, len(string)):
    if string[i] == current_char:
        count += 1
    else:
        encoded_string += str(count) + current_char
        current_char = string[i]
        count = 1

encoded_string += str(count) + current_char

print("Encoded:", encoded_string)